---

- name: Install required tools
  apt:  pkg={{ item }}
        state=present
        update_cache=yes
  with_items: "{{ kallithea_required_tools }}"
  tags:
    - kallithea_install_required_tools

- name: Add Kallithea system user
  user: name={{ kallithea_user }} shell=/bin/bash
        system=yes
  tags:
    - kallithea_install_user

- name: Create repositories directory
  file: path={{ kallithea_repodir }} state=directory
        owner={{ kallithea_user }}
        group={{ kallithea_user }}
  tags:
    - kallithea_install_repodir

- name: Create log directory
  file: path={{ kallithea_logdir }} state=directory
        owner=root group={{ kallithea_user }}
        mode=770 force=no
  tags:
    - kallithea_install_logdir

# Some issues encountered when installing kallithea directly
- name: virtualenv - install six at first
  become_user: "{{ kallithea_user }}"
  pip:  name=six
        virtualenv={{ kallithea_venv }}

- name: virtualenv - install kallithea
  become_user: "{{ kallithea_user }}"
  pip:  name=kallithea
        version={{ kallithea_version }}
        virtualenv={{ kallithea_venv }}

- name: Set the 'kallithea_config_sqlalchemy_db1_url' variable from options
  set_fact:
    kallithea_config_sqlalchemy_db1_url: |
        {% set vars = {'result': 'sqlite'} %}
        {% for item in kallithea_config_options %}
            {% for option in item.options %}
                {% if option.option == 'sqlalchemy.db1.url' %}
                    {% if vars.update({'result': option.value}) %}{% endif %}
                {% endif %}
            {% endfor %}
        {% endfor %}
        {{ vars['result'] }}

- name: Cleanup the 'kallithea_config_sqlalchemy_db1_url' value
  set_fact:
    kallithea_config_sqlalchemy_db1_url: "{{ kallithea_config_sqlalchemy_db1_url.strip() }}"
