---

- include: install.yml
  tags:
    - kallithea
    - kallithea_install

- include: postgresql.yml
  when: kallithea_config_sqlalchemy_db1_url.startswith('postgresql')
  tags:
    - kallithea
    - kallithea_postgresql

- include: config.yml
  tags:
    - kallithea
    - kallithea_config

- include: logrotate.yml
  tags:
    - kallithea
    - kallithea_logrotate

- include: service.yml
  tags:
    - kallithea
    - kallithea_service
