---

- include_tasks: install.yml
  tags:
    - kallithea
    - kallithea_install

- include_tasks: postgresql.yml
  when: kallithea_config_sqlalchemy_db1_url.startswith('postgresql')
  tags:
    - kallithea
    - kallithea_postgresql

- include_tasks: config.yml
  tags:
    - kallithea
    - kallithea_config

- include_tasks: logrotate.yml
  tags:
    - kallithea
    - kallithea_logrotate

- include_tasks: service.yml
  tags:
    - kallithea
    - kallithea_service
