---

- name: PostgreSQL - Install required tools
  apt: pkg={{ item }}
        state=installed
  with_items:
    - postgresql-server-dev-all
    - python-psycopg2

- name: virtualenv - Install psycopg2
  become_user: "{{ kallithea_user }}"
  pip:  name={{ item }}
        virtualenv={{ kallithea_venv }}
  with_items:
    - psycopg2

- name: Delegate PostgreSQL tasks to the relevant host
  set_fact:
    kallithea_postgresql_delegate_to: "{{ kallithea_db_host if ((kallithea_db_host|bool) != False) else inventory_hostname }}"
    kallithea_postgresql_remote_user: "{{ kallithea_db_host_user if ((kallithea_db_host|bool) != False) else ansible_user }}"

- block:

    - name: PostgreSQL - Add user
      postgresql_user: name={{ kallithea_db_user }}
                       role_attr_flags=CREATEDB,NOSUPERUSER

    - name: PostgreSQL - Set user password
      postgresql_user: name={{ kallithea_db_user }}
                       password={{ kallithea_db_passwd }}
      when: kallithea_db_passwd is defined and kallithea_db_passwd

    - name: PostgreSQL - Create database
      postgresql_db:    name={{ kallithea_db_name }}
                        owner={{ kallithea_db_user }}

  delegate_to: "{{ kallithea_postgresql_delegate_to }}"
  remote_user: "{{ kallithea_postgresql_remote_user }}"
  become: yes
  become_user: postgres
