---

- name: Setup init script
  template: src=kallithea.init.j2
            dest=/etc/init.d/{{ kallithea_service_name }}
            owner=root group=root mode=0755
            backup=yes

- name: Enable service
  service:  name={{ kallithea_service_name }}
            enabled=yes
            state=started
  when: kallithea_service_init == True

- name: Disable service
  service:  name={{ kallithea_service_name }}
            enabled=no
            state=stopped
  when: kallithea_service_init == False
